### ISSUE TITLE
date/time issues

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/GLRI_CEC_2016#25]
- Some dates in `chemicalSummary_conc` are `NA` vals. Track down what's going on here.

- Why do some reported concentrations have different time stamps? e.g., get more than one unique combination of site-dates.

**Comment by srcorsi-USGS** [comment]
The dates should all be represented in the tracking form here:
https://drive.google.com/drive/folders/0B_E77yZb-7adVVhjSnpCSGRlS1E
If they are not, let me know which ones, and we can track them down.
Not sure about item 2, but perhaps the tracking form will help understand that as well?

**Comment by limnoliver** [comment]
Thanks @srcorsi-USGS - it looks like the duplicate dates may be QA samples taken on the same day but have different time stamps. Will dig into this.
