### ISSUE TITLE
pesticide data issues

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/GLRI_CEC_2016#29]
After pull from NWIS, compared NWIS data to tracking data and came up with the following inconsistencies:

**In tracking but not NWIS:**

- ~~Milwaukee River, site 04087170, on date 2016-04-07 _[But, see below]_~~

- ~~Indiana Harbor Canal, site 04092750, on date 2016-08-02~~

**In NWIS but not in tracking:** 

- ~~Milwaukee River, site 04087170, on date 2016-04-05 _Guessing this is missing data from above, should change date to reconcile_~~

- ~~a bunch of Maumee, site 04193500, on dates 2016-05-03 (only a single compounds, may be wrong date), 2016-06-02, 2016-06-14, 2016-06-21, 2016-07-20, 2016-08-25. @srcorsi-USGS was there more intensive sampling done by some other group on the Maumee that is not captured in the tracking? If so, should we use this data?~~ 

**Other issues**
- Indiana Harbor Canal, site 04092750, on date 2016-08-02 has duplicate samples -- appear to be the exact same information.
- Two atrazine values from the Maumee, site 04193500, on date 2016-06-07. There are not two measures of anythign else at that site/date.

**Comment by srcorsi-USGS** [comment]
Yes, Maumee was sampled by NAWQA more intensively than we sampled the rest of our sites. Yes, we should use this data. We were in touch with the NAWQA folks during the design phase of this study and leveraged their data collection effort. We will need to include an acknowledgment in the manuscript for this.

**Comment by limnoliver** [comment]
Thanks! One mystery solved...

**Comment by srcorsi-USGS** [comment]
Same evaluation method as glyphosate

Milwaukee River: 4/5/2016 is correct

IHC: Not sure why this does not show in NWIS. It is in the NWQL sample status page here:
http://wwwnwql.cr.usgs.gov/. Results attached.

I will send a note to our Indiana contact.

[sampstatusIHCAug2016.xlsx](https://github.com/USGS-R/GLRI_CEC_2016/files/2098840/sampstatusIHCAug2016.xlsx)

**Comment by limnoliver** [comment]
The replicate atrazine issue was [fixed manually](https://github.com/limnoliver/GLRI_CEC_2016/blob/master/20_merge_data/src/merge_data.R#L88) by filtering out the second observation which appears to be a replicate.

**Comment by limnoliver** [comment]
Duplicate measures at site IHC resolved in NWIS.
