### ISSUE TITLE
glyphosate data issues

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/GLRI_CEC_2016#30]
Compared glyphosate pull from NWIS to tracking:

**In tracking but not NWIS**

- ~~Milwaukee River, site 04087170, on date 2016-04-07 _[but see below]_~~

- ~~Indiana Harbor Canal, site 04092750, on dates 2016-02-02 and 2016-04-04~~

**In NWIS but not tracking**

- ~~Milwaukee River, site 04087170, on date 2016-04-05 _[I assume this is missing data from above, should change to reconcile]_~~

- ~~Maumee River, site 04193500: In some instances, there is a regular log from tracking, but did not indicate that glyphosate was collected (on dates 2015-11-04, 2015-12-02, 2016-01-07, 2016-03-03, 2016-05-10, 2016-08-02, 2016-09-07). In other instances, there is no log in tracking, which is presumably the NAWQA-collected samples (on dates 2016-06-02, 2016-06-14, 2016-06-21, 2016-07-20, 2016-08-25)~~

**Other issues**

- Maumee River, site 04193500, on date 2016-02-02: repeated glyphosate measurements (for full glyphosate method (62722) and degradate (62649)) with same date/time stamp. Tracking does not show duplicate measures that day. Values are similar but not the same. Could this possibly be missing IHC site data from 2016-02-02?

**Comment by srcorsi-USGS** [comment]
How these were evaluated: 
1. Examine dates for other WI sites nearby (Manitowoc and Fox). These were always done during the same field trip
2. Review copies of the lab submittal forms here: M:\QW Monitoring Team\GLRI toxics\GLRI II\WY2016\Field WY16\Completed ASRs and lab forms

Milwaukee: 4/5/2016 date is correct

IHC: 02/02/2016 is reported in the spreadsheet (only IMG) that the Kansas lab sent use. concentration = <0.10
4/4. It is not in the final spreadsheet, but does show up in an earlier preliminary spreadsheet with concentration = <0.1.  I am following up with the Kansas lab on this.

Maumee 04193500: Assume these are all NAWQA and let's use them as they are in NWIS

Maumee 04193500: We did not do any full glyphosate analyses during Feb-2016, so these must be from NAWQA. We only did IMG for glyphosate that month for the whole project.

**Comment by srcorsi-USGS** [comment]
In the tracking form, the site ID is 04092750 for IHC. Where did 04092720 come from? As far as I can tell, that site number does not exist. I checked the NWIS mapper and tried using dataRetrieval with no positive results. @limnoliver

**Comment by limnoliver** [comment]
@srcorsi-USGS -- this was a typing mistake. SiteID for IHC in the data and tracking is 04092750. I changed the original issue to reflect the correct ID.

**Comment by srcorsi-USGS** [comment]
Kansas has resubmitted the IHC samples for upload to NWIS. For now, just add those into the analysis within the code. They are both <0.10. @limnoliver
