### ISSUE TITLE
chemicals without casrns

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/GLRI_CEC_2016#33]
Many chemicals with out CAS numbers. Appears that Laura originally filtered these out, as I am doing during formation of `chem_data` target in `20_merge_data.yml`.

Is this correct? Can we not evaluate with toxEval if there are no CAS numbers?

**Comment by srcorsi-USGS** [comment]
Let's develop a list of these chemicals and investigate a bit further. Some may have CAS nums that we currently don't have documented. In addition, chemicals that do have CAS nums, but do not appear in ToxCast may have more than one CAS num associated with that given compound. Let's talk about ways to look into this. My first suggestion would be to look at the CompTox web page. This is now the go-to page for tons of info on chemicals and chemical properties.

**Comment by limnoliver** [comment]
Fifteen chemicals do not have CAS numers. From what I can tell by cross-referencing CompTox, these legitimately do not have assigned CAS numbers, as I looked at alternative/root names and could not find more info. Further, googling these chemical names mostly leads to USGS documentation, not any additional info on these compounds. 

![image](https://user-images.githubusercontent.com/15788176/42586449-c0ffbdf6-84fd-11e8-8747-1b039f0f31ad.png)

**Comment by srcorsi-USGS** [comment]
Looks like most (all?) of them are degradation products, so not too surprising. Looks like time to let it go and move on from here.

**Comment by limnoliver** [comment]
Further, only two of these chemicals were detected. Tebuthiuron transformation product 104 was detected once and dimethenamid oxanilic acid was detected 7 times.
